// ASS template constants. Ported verbatim from the original Ghost page; only
// the magic numbers (screenX, screenY, fontSize, durations, spacing) are now
// parameters with the same defaults.
//
// IMPORTANT: the original template has trailing single spaces on lines like
// `Title: ` and `Original Script: ` (because the upstream file we ported
// from did). To keep byte-level diff with the original, we build those lines
// programmatically here so editors won't strip the trailing spaces.

import type { ResolvedOptions } from './types.js';

export const DEFAULT_OPTIONS: ResolvedOptions = {
  offset: 0,
  screenX: 1920,
  screenY: 1080,
  spaceHeight: 50,
  centerOffsetY: 140,
  danmutime: 10,
  danmutimeFixed: 5,
  fontSize: 40,
};

/** Resolve user-supplied options against the defaults. */
export function resolveOptions(opts: Partial<ResolvedOptions> = {}): ResolvedOptions {
  return { ...DEFAULT_OPTIONS, ...opts };
}

const SP = ' ';

/**
 * Render the ASS file's leading boilerplate and Style block. The returned
 * string contains two literal placeholders:
 *   - `{{style}}`     → injected per-color Style lines
 *   - `{{subtitle}}`  → injected Dialogue lines
 *
 * Trailing whitespace on header metadata lines mirrors the original byte
 * sequence so a generated ASS can be diff'd against an Aegisub-r8942 file
 * produced by the legacy Ghost page.
 */
export function buildTemplate(opts: ResolvedOptions): string {
  const { screenX, screenY, fontSize } = opts;
  const lines: string[] = [
    '',
    '[Script Info]',
    '; Script generated by Aegisub r8942',
    '; http://www.aegisub.org/',
    'ScriptType: v4.00+',
    'ScaledBorderAndShadow: no',
    `PlayResX: ${screenX}`,
    `PlayResY: ${screenY}`,
    'Timer: 100.0000',
    'Title:' + SP,
    'Original Script:' + SP,
    'Original Translation:' + SP,
    'Original Editing:' + SP,
    'Original Timing:' + SP,
    'Script Updated' + SP,
    'Update Details:' + SP,
    'WrapStyle: 0',
    'YCbCr Matrix: TV.601',
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    'Style: ED_JP,TelopMinProN-E,60,&H19FFFFFF,&H000000FF,&H00000000,&H19000000,0,0,0,0,100,100,1,0,1,1.5,1,8,50,50,30,1',
    'Style: ED_SC,SourceHanSerifSC-Bold,55,&H19FFFFFF,&H000000FF,&H00000000,&H19000000,0,0,0,0,100,100,4.5,0,1,1.5,1,2,50,50,40,1',
    'Style: ED_TC,SourceHanSerifK-Bold,55,&H19FFFFFF,&H000000FF,&H00000000,&H19000000,0,0,0,0,100,100,4.5,0,1,1.5,1,2,50,50,40,1',
    `Style: Main,FZLiBian-S02,${fontSize},&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,-1,0,0,0,100,100,2,0,1,2,2,2,60,60,30,1`,
    'Style: Story,FZKai-Z03,55,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,-1,0,0,0,100,100,3,0,1,2,2,2,60,60,30,1',
    'Style: Annotation_SC,SourceHanSerifSC-Bold,40,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,1,7,30,30,30,1',
    'Style: Annotation_TC,SourceHanSerifK-Bold,40,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,1,7,30,30,30,1',
    'Style: Staff_SC,SourceHanSerifSC-Bold,40,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,1,8,30,30,30,1',
    'Style: Staff_TC,SourceHanSerifK-Bold,40,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,1,8,30,30,30,1',
    'Style: Draw,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,2,10,10,10,1',
    '{{style}}',
    '',
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
    '{{subtitle}}',
    '  ',
  ];
  return lines.join('\n');
}
