// Emit Cloudflare Pages-format `_redirects` from all redirect sources.
// usage: tsx scripts/emit-redirects.ts

import { isMain, readJson, repoPath, writeFileIfChanged } from './_lib.ts';

interface RedirectEntry {
  from: string;
  to: string;
  status: 301 | 302 | 410;
}

/* WordPress residue pages — friendlier 301 → / per design D10. */
const WP_RESIDUE_REDIRECTS: RedirectEntry[] = [
  { from: '/sample-page/', to: '/', status: 301 },
  { from: '/pie-register-forgot-password/', to: '/', status: 301 },
  { from: '/pie-register-profile/', to: '/', status: 301 },
  { from: '/registration/', to: '/', status: 301 },
  { from: '/login-post/', to: '/', status: 301 },
];

/* Ghost-only paths that no longer exist on the static site. */
const GHOST_GONE: RedirectEntry[] = [
  { from: '/ghost/*', to: '/', status: 410 },
  { from: '/p/*', to: '/', status: 410 },
  { from: '/email/*', to: '/', status: 410 },
  { from: '/members/*', to: '/', status: 410 },
];

/** Convert a Ghost-style admin redirect entry into our canonical shape. */
function normaliseAdminRedirect(raw: unknown): RedirectEntry | null {
  if (!raw || typeof raw !== 'object') return null;
  const obj = raw as Record<string, unknown>;
  const from = typeof obj.from === 'string' ? obj.from : null;
  const to = typeof obj.to === 'string' ? obj.to : null;
  if (!from || !to) return null;
  let status: RedirectEntry['status'] = 301;
  if (typeof obj.permanent === 'boolean') {
    status = obj.permanent ? 301 : 302;
  }
  if (typeof obj.status === 'number') {
    if (obj.status === 301 || obj.status === 302 || obj.status === 410) {
      status = obj.status;
    }
  }
  return { from, to, status };
}

function dedupe(entries: RedirectEntry[]): RedirectEntry[] {
  const seen = new Set<string>();
  const out: RedirectEntry[] = [];
  for (const r of entries) {
    const key = `${r.from}::${r.to}::${r.status}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(r);
  }
  return out;
}

/**
 * Format a single redirect line in Cloudflare Pages syntax.
 * Splat captures (`*`) on the left translate to `:splat` on the right.
 * For pure-410 rules CF lets us write `from / 410` (the `to` becomes a placeholder).
 */
export function formatLine(r: RedirectEntry): string {
  const from = r.from.trim();
  const to = r.to.trim();
  return `${from} ${to} ${r.status}`;
}

export interface EmitStats {
  total: number;
  written: boolean;
}

export function runEmitRedirects(): EmitStats {
  const pending = readJson<RedirectEntry[]>(
    repoPath('import-cache', 'redirects-pending.json'),
    [],
  );
  const sourceRaw = readJson<unknown[]>(
    repoPath('import-cache', 'redirects-source.json'),
    [],
  );
  const ghostAdmin = sourceRaw
    .map(normaliseAdminRedirect)
    .filter((x): x is RedirectEntry => x !== null);

  // Order: tag rename + Ghost-admin first (most specific), then WP residue,
  // then catch-all 410 patterns. Within `_redirects`, the first match wins.
  const merged = dedupe([
    ...pending,
    ...ghostAdmin,
    ...WP_RESIDUE_REDIRECTS,
    ...GHOST_GONE,
  ]);

  const header = [
    '# Auto-generated by scripts/emit-redirects.ts — do not edit by hand.',
    '# Sources: import-cache/redirects-pending.json + import-cache/redirects-source.json',
    '#          + WordPress residue rules + Ghost-only path 410s.',
  ].join('\n');
  const body = merged.map(formatLine).join('\n');
  const content = `${header}\n${body}\n`;
  const wrote = writeFileIfChanged(repoPath('public', '_redirects'), content);

  console.log(
    `[emit-redirects] total: ${merged.length} (pending: ${pending.length}, ` +
      `ghost-admin: ${ghostAdmin.length}, wp-residue: ${WP_RESIDUE_REDIRECTS.length}, ` +
      `ghost-gone: ${GHOST_GONE.length}) — ${wrote ? 'wrote' : 'unchanged'}`,
  );

  return { total: merged.length, written: wrote };
}

if (isMain(import.meta.url)) {
  try {
    runEmitRedirects();
  } catch (err) {
    console.error('[emit-redirects] failed:', err);
    process.exit(1);
  }
}
